### ISSUE TITLE
Snap version displays unreadable/misplaced fonts in KDE Plasma running wayland

### ISSUE THREAD

**Issue by rikvermeer** [eneshecan/whatsapp-for-linux#230]
**Description**
Snap version displays unreadable/misplaced fonts in KDE Plasma running wayland

**Solution**
Build from GIT

**To Reproduce**
Install whatsapp-for-linux by snap under KDE plasma
Install plasma-wayland-session
Enable wayland on session login (lower left corner)
Start WA

**Expected behavior**
Readable fonts

**Screenshots**
![image](https://user-images.githubusercontent.com/2795570/197183217-8a479186-1aff-42d6-b9fa-352ad62563c4.png)

**Environment**
 - Manjaro / Arch
 - snap
 - KDE Plasma
 - wayland

**Comment by rikvermeer** [comment]
Fixed by compiling from source. 
Looks wonderful again <3

**Comment by Eyap53** [comment]
Got the same problem with flatpak

**Comment by eneshecan** [comment]
Does this issue still persist with 1.5.0?

**Comment by jrr45** [comment]
It is still present in 1.5.0 for me.

My setup:
-     Kubuntu 22.10
-     flatpak
-     KDE Plasma 5.25.5
-     wayland

**Comment by Eyap53** [comment]
I also still have this issue.

**Comment by Eyap53** [comment]
Still present in 1.5.1

**Comment by eneshecan** [comment]
Could you please check whether your gtk-3 settings are correctly set up for your system? Should be in your .config/gtk-3.0 folder

**Comment by Eyap53** [comment]
Well, it seems ok I guess :

```
[Settings]
gtk-application-prefer-dark-theme=true
gtk-button-images=true
gtk-cursor-theme-name=breeze_cursors
gtk-cursor-theme-size=24
gtk-decoration-layout=icon:minimize,maximize,close
gtk-enable-animations=true
gtk-font-name=Noto Sans,  10
gtk-icon-theme-name=breeze
gtk-menu-images=true
gtk-modules=colorreload-gtk-module
gtk-primary-button-warps-slider=false
gtk-toolbar-style=3
```

On a side note, building the app myself produced the expected result

**Comment by eneshecan** [comment]
Hmmm, there should be no comma between the font name and size but only a space.

**Comment by Eyap53** [comment]
I tried to play around with the values, but it seems like no changes are reflected in the app (each time I restarted the flatpak app).

**Comment by eneshecan** [comment]
Similar problem here #138

**Comment by eneshecan** [comment]
Could someone please try with a071a5c ?
